# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7427cb0dc855c57c33cca5c9cae8e0c6"
name = "remix-test"
handle = "remix-test-69"
application_url = "https://pairs-fig-smooth-combine.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hydrogen-first.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pairs-fig-smooth-combine.trycloudflare.com/auth/callback",
  "https://pairs-fig-smooth-combine.trycloudflare.com/auth/shopify/callback",
  "https://pairs-fig-smooth-combine.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
